version: '2'
services:
  config-service:
    image: springdocdemos/config-service:latest
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
        -DCONFIG_SERVER=http://config-service:8088
    ports:
      - 8088:8088
  discovery-service:
    image: springdocdemos/discovery-service:latest
    ports:
      - 8761:8761
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
        -DCONFIG_SERVER=http://config-service:8088
  employee-service:
    image: springdocdemos/employee-service:latest
    ports:
      - 8092:8092
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
        -DCONFIG_SERVER=http://config-service:8088
    depends_on:
      - discovery-service
      - config-service
  gateway-service:
    image: springdocdemos/gateway-service:latest
    ports:
        - 8060:8060
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery-service:8761/eureka
        -DCONFIG_SERVER=http://config-service:8088
    depends_on:
      - discovery-service
      - config-service